### ISSUE TITLE
Not work on Win 10 Py 3.11

### ISSUE THREAD

**Issue by milen-prg** [tipam/pi3d#261]
Windows 10 Pro 64bit, Python 3.11.3, pi3d 2.49, at try to

import pi3d

Result is ERROR:

Couldn't load library ./libglesv2.dll
Couldn't load library ./libegl.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python311\Lib\site-packages\pi3d\__init__.py", line 10, in <module>
    from pi3d.constants import (USE_PYGAME, PIL_OK,
  File "C:\Python311\Lib\site-packages\pi3d\constants\__init__.py", line 198, in <module>
    PLATFORM, bcm, openegl, opengles = _detect_platform_and_load_libraries()
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pi3d\constants\__init__.py", line 190, in _detect_platform_and_load_libraries
    platform, bcm, openegl, opengles = loader()
                                       ^^^^^^^^
  File "C:\Python311\Lib\site-packages\pi3d\constants\__init__.py", line 156, in _windows
    openegl.eglGetDisplay.argtypes = [wt.HDC]
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'eglGetDisplay'

**Comment by paddywwoof** [comment]
Hi @milen-prg did you put the relevant ANGLE libraries to somewhere the python script can find them? i.e. along the lines of https://github.com/tipam/pi3d#windows

Let me know any other info of your setup and I will try to help

**Comment by milen-prg** [comment]
I apologize, missed this part. When I copied the dlls from https://github.com/paddywwoof/pi3d_windll, all start to work.
Thank, you!

P.S. Is it possible to include the necessary dlls in the pi3d pypi installation packet?
